spring.application.name=nextconsulting

spring.datasource.url=jdbc:postgresql://localhost:5434/nextconsulting
spring.datasource.username=postgres
spring.datasource.password=5501

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true